version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "appuser", "-papppass"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet

  php:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - mysql
    volumes:
      - ./api:/var/www/api
    networks:
      - appnet

  nginx:
    image: nginx:stable
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: node
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    ports:
      - "5173:5173"
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge